<a target="_blank" href="https://colab.research.google.com/github/vnstock-hq/vnstock_insider_guide/blob/main/demo/1-vnstock_data_explorer_v2_demo.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# I. Cài đặt thư viện

In [ ]:
# Sao chép mã nguồn từ GitHub về Google Colab
!git clone https://github.com/vnstock-hq/vnstock_insider_guide
# Chuyển đến thư mục vừa clone
%cd /content/vnstock_insider_guide/oneclick_installer
# Trao quyền thực thi cho file
!chmod +x linux_installer.run
# Chạy trình cài đặt
!./linux_installer.run

**Lưu ý: Bạn cần khởi động lại phiên làm việc sau khi cài đặt trên Google Colab**

![restar session](http://localhost:3000/images/khoi-dong-lai-phien-lam-viec-colab.png)

# II. Minh hoạ

## 1. Thống kê giao dịch

In [ ]:
from vnstock_data import Trading
trading = Trading(symbol='MSN')
START_DATE = '2024-08-01'
END_DATE = '2024-08-16'

### Lịch sử giá

In [2]:
trading.price_history(start=START_DATE, end=END_DATE)

2025-03-27 23:15:54 - vnstock_data.explorer.cafef.trading - INFO - Lịch sử giá:
Mã CK: MSN. Số bản ghi hợp lệ: 12

,open,high,low,close,adjusted_price,change_pct,matched_volume,matched_value,deal_volume,deal_value
time,,,,,,,,,,
2024-08-16,75.4,77.5,75.2,77.3,77.3,0.0307,8146700,624175000000,39,2983500
2024-08-15,76.7,76.7,75.0,75.0,75.0,-0.0196,3319900,250972000000,155053,11597964400
2024-08-14,75.2,77.3,74.9,76.5,76.5,0.0227,10253700,785205000000,11,827200
2024-08-13,75.0,75.2,73.8,74.8,74.8,-0.0053,4760200,354087000000,155000,11594000000
2024-08-12,75.5,76.2,74.3,75.2,75.2,0.0000,4458500,335256000000,0,0
2024-08-09,74.6,75.3,74.5,75.2,75.2,0.0094,3965800,297022000000,0,0
2024-08-08,73.0,75.6,72.7,74.5,74.5,0.0205,9533100,711827000000,0,0
2024-08-07,73.3,73.5,72.2,73.0,73.0,-0.0027,3653400,266130000000,4876000,356849600000
2024-08-06,71.0,73.4,70.5,73.2,73.2,0.0383,5272100,380075000000,259000,18699800000
2024-08-05,71.3,72.7,70.2,70.5,70.5,-0.0235,6260600,444531000000,20000,1544000000
2024-08-02,71.0,73.2,71.0,72.2,72.2,0.0056,5314700,383544000000,259000,18699800000
2024-08-01,74.1,74.9,70.8,71.8,71.8,-0.0310,7659500,561882000000,0,0

### Thống kê đặt lệnh

In [3]:
trading.order_stats(start=START_DATE, end=END_DATE)

2025-03-27 23:15:54 - vnstock_data.explorer.cafef.trading - INFO - Thống kê đặt lệnh:
Mã CK: MSN. Số bản ghi hợp lệ: 11

,buy_orders,sell_orders,buy_volume,sell_volume,volume_diff,avg_buy_order_volume,avg_sell_order_volume
time,,,,,,,
2024-08-16,6520,6883,13304200,14321700,"-1,017,500",2040.52,2081
2024-08-15,4771,3794,5750400,8095400,"-2,345,000",1205.28,2134
2024-08-14,7007,11031,23704400,20139000,"3,565,400",3382.96,1826
2024-08-13,6559,3650,8846800,8600300,"246,500",1348.80,2356
2024-08-12,5403,4727,8667000,9060700,"-393,700",1604.11,1917
2024-08-08,7018,9430,18987700,17592900,"1,394,800",2705.57,1866
2024-08-07,4375,5013,6947100,6589000,"358,100",1587.91,1314
2024-08-06,4557,5189,9752900,9474100,"278,800",2140.20,1826
2024-08-05,8693,4095,10187100,10429300,"-242,200",1171.87,2547
2024-08-02,6137,3851,11814700,9103100,"2,711,600",1925.16,2364
2024-08-01,7786,5423,13009600,13948900,"-939,300",1670.90,2572

### Giao dịch nước ngoài

In [4]:
trading.foreign_trade(start=START_DATE, end=END_DATE)

2025-03-27 23:15:54 - vnstock_data.explorer.cafef.trading - INFO - Lịch sử GD Nước ngoài:
Mã CK: MSN. Số bản ghi hợp lệ: 12

,fr_net_volume,fr_net_value,fr_buy_volume,fr_buy_value,fr_sell_volume,fr_sell_value,fr_remaining_room,fr_ownership
time,,,,,,,,
2024-08-16,819800,63190100000,1352500,103867230000,532700,40677130000,309182209,28.56
2024-08-15,-241800,-18319590000,188800,14299490000,430600,32619080000,310321038,28.49
2024-08-14,2855600,218659620000,3069200,235054510000,213600,16394890000,309878586,28.52
2024-08-13,59700,4541660000,684900,51044810000,625200,46503150000,312328492,28.36
2024-08-12,-275700,-20993260000,343500,25750980000,619200,46744240000,312345060,28.35
2024-08-09,472860,35386737800,1141200,85418280000,668340,50031542200,312368360,28.35
2024-08-08,1036300,77000610000,1392500,103700660000,356200,26700050000,312749186,28.33
2024-08-07,-436200,-31788990000,379100,27580810000,815300,59369800000,313847386,28.26
2024-08-06,582500,42572070000,876800,63640240000,294300,21068170000,313982629,28.25
2024-08-05,681200,48343730000,924900,65670630000,243700,17326900000,314436493,28.22
2024-08-02,848200,61147120000,1271100,91686810000,422900,30539690000,315126598,28.17
2024-08-01,1133200,83515230000,1368000,100646570000,234800,17131340000,315745298,28.13

### Thống kê giao dịch tự doanh

In [5]:
trading.prop_trade(start=START_DATE, end=END_DATE)

2025-03-27 23:15:55 - vnstock_data.explorer.cafef.trading - INFO - Lịch sử GD Tự Doanh:
Mã CK: MSN. Số bản ghi hợp lệ: 12

            prop_buy_volume  prop_sell_volume  prop_buy_value  prop_sell_value
time
2024-08-16           308300            631400     23701000000      48405990000
2024-08-15           151500            144200     11463000000      10915430000
2024-08-14           189000            373600     14503110000      28500230000
2024-08-13           321600            114400     23882040000       8534700000
2024-08-12           149700            242200     11233030000      18232480000
2024-08-09            95000             91700      7103840000       6865100000
2024-08-08           158600            617200     11838100000      46065230000
2024-08-07            64900            284400      4718110000      20741850000
2024-08-06           509800            185000     36493820000      13408000000
2024-08-05           161300            767500     11444560000      54692540000
2024-08-02           129000            328900      9323420000      23729710000
2024-08-01           634000            277400     46819530000      20285700000

### Thống kê giao dịch nội bộ

In [6]:
trading.insider_deal(start='2024-01-02', end=END_DATE)

2025-03-27 23:15:55 - vnstock_data.explorer.cafef.trading - INFO - Thống kê giao dịch Cổ Đông & Nội bộ:
Mã CK: MSN. Số bản ghi hợp lệ: 6
invalid value encountered in cast
invalid value encountered in cast
invalid value encountered in cast

,symbol,holder_id,transaction_man,transaction_man_position,related_man_position,related_man,volume_before_transaction,plan_buy_volume,plan_sell_volume,plan_begin_date,plan_end_date,real_buy_volume,real_sell_volume,real_end_date,published_date,order_date,volume_after_transaction,transaction_note,shareholder_code,ownership_percentage
0,MSN,0,Trần Phương Bắc,Công bố thông tin,,,137040,71028,0,2024-06-17 17:00:00,2024-06-17 17:00:00,0,0,NaT,2024-06-14 04:13:38.783,2024-06-17 17:00:00,0,,CEO_80830,0.000000
1,MSN,0,Danny Le,Tổng Giám đốc,,,3408644,292211,0,2024-06-17 17:00:00,2024-06-17 17:00:00,0,0,NaT,2024-06-14 04:10:33.750,2024-06-17 17:00:00,0,,CEO_36172,0.000000
2,MSN,0,Nguyễn Huy Hùng,Kế toán trưởng,,,50799,70666,0,2024-06-17 17:00:00,2024-06-17 17:00:00,0,0,NaT,2024-06-14 04:12:43.497,2024-06-17 17:00:00,0,,CEO_871208,0.000000
3,MSN,0,Đoàn Thị Mỹ Duyên,Giám đốc Tài chính,,,653235,20431,0,2024-06-17 17:00:00,2024-06-17 17:00:00,0,0,NaT,2024-06-14 04:11:26.193,2024-06-17 17:00:00,0,,CEO_30750,0.000000
4,MSN,0,Michael Hung Nguyen,Giám đốc Tài chính,,,3533058,132349,0,2024-06-17 17:00:00,2024-06-17 17:00:00,0,0,NaT,2024-06-14 04:12:09.167,2024-06-17 17:00:00,0,,CEO_70174,0.000000
5,MSN,0,GIC/Government of Singapore,,,,32188724,0,0,NaT,NaT,0,545800,2024-03-12 17:00:00,2024-03-25 03:49:05.140,2024-03-12 17:00:00,31642924,,GICSINGAPORE,2.199944

## 2. Giá lịch sử (đã điều chỉnh) & thống kê giao dịch trong ngày (intraday)

### VND

In [25]:
# Dữ liệu từ VND
from vnstock_data import Quote

quote = Quote(symbol='REE')
quote.history(start='2000-07-28', end='2024-08-31', interval='1D')

           time   close    open    high     low   volume
0    2013-01-02   6.058   5.987   6.094   5.987   421680
1    2013-01-03   5.987   6.023   6.094   5.952   624970
2    2013-01-04   6.058   5.987   6.094   5.952   314290
3    2013-01-07   6.094   6.058   6.201   6.058   497270
4    2013-01-08   6.379   6.058   6.379   6.058  1872200
...         ...     ...     ...     ...     ...      ...
2904 2024-08-26  69.048  70.330  70.626  68.456   676600
2905 2024-08-27  67.667  68.653  69.048  67.470   692400
2906 2024-08-28  67.667  67.766  68.062  67.272   530200
2907 2024-08-29  68.062  67.568  68.062  67.470   328800
2908 2024-08-30  67.667  67.766  68.259  67.568   342100

[2909 rows x 6 columns]

In [26]:
quote.intraday()

,time,price,accumulated_val,accumulated_vol,volume,match_type
0,2025-03-27 09:15:03,72.0,252000000,3500,3500,ATO
1,2025-03-27 09:15:04,72.0,266400000,3700,100,Buy
2,2025-03-27 09:15:04,72.0,259200000,3600,100,Buy
3,2025-03-27 09:15:04,72.0,324000000,4500,800,Buy
4,2025-03-27 09:17:08,72.4,338480000,4700,200,Sell
...,...,...,...,...,...,...
844,2025-03-27 14:29:16,72.9,35829650000,490800,200,Sell
845,2025-03-27 14:29:24,72.8,35866050000,491300,100,Buy
846,2025-03-27 14:29:24,72.8,35858770000,491200,200,Buy
847,2025-03-27 14:29:24,72.8,35844210000,491000,200,Buy
848,2025-03-27 14:45:01,73.1,37583900000,514800,23500,ATC

### VCI

Dữ liệu tại mục này tương đương hàm có trong Vnstock bản Public tuy nhiên được nâng cấp 10X giới hạn rate limit (số requests được phép trong một khung thời gian)

In [27]:
# Dữ liệu từ VCI

from vnstock_data.explorer.vci import Quote

quote = Quote(symbol='REE')
quote.history(start='2000-07-28', end='2024-08-31', interval='1D')

           time   open   high    low  close  volume
0    2000-07-28   0.53   0.53   0.53   0.53    1000
1    2000-07-31   0.54   0.54   0.54   0.54     300
2    2000-08-02   0.55   0.55   0.55   0.55     100
3    2000-08-04   0.56   0.56   0.56   0.56     200
4    2000-08-07   0.57   0.57   0.57   0.57    2800
...         ...    ...    ...    ...    ...     ...
5849 2024-08-26  70.33  70.63  68.46  69.05  678177
5850 2024-08-27  68.65  69.05  67.47  67.67  694135
5851 2024-08-28  67.77  68.06  67.27  67.67  531151
5852 2024-08-29  67.57  68.06  67.47  68.06  329921
5853 2024-08-30  67.77  68.26  67.57  67.67  342819

[5854 rows x 6 columns]

In [28]:
# Dữ liệu từ VCI
quote.intraday()

                        time    price  volume match_type         id
0  2025-03-27 14:18:19+07:00  73200.0     100        Buy  282830685
1  2025-03-27 14:18:19+07:00  73200.0     100        Buy  282830686
2  2025-03-27 14:18:23+07:00  73100.0     400       Sell  282830745
3  2025-03-27 14:18:23+07:00  73100.0     400       Sell  282830747
4  2025-03-27 14:18:23+07:00  73100.0     400       Sell  282830744
..                       ...      ...     ...        ...        ...
95 2025-03-27 14:29:16+07:00  72900.0     200        Buy  282854335
96 2025-03-27 14:29:24+07:00  72800.0     200       Sell  282854682
97 2025-03-27 14:29:24+07:00  72800.0     200       Sell  282854683
98 2025-03-27 14:29:24+07:00  72800.0     100       Sell  282854684
99 2025-03-27 14:45:01+07:00  73100.0   23500        ATC  282856769

[100 rows x 5 columns]

## 3. Báo cáo tài chính

Dữ liệu tại mục này tương đương hàm có trong Vnstock bản Public tuy nhiên được nâng cấp 10X giới hạn rate limit (số requests được phép trong một khung thời gian)

In [31]:
from vnstock_data.explorer.vci import Finance
fin = Finance(symbol='VCI')

### Bảng cân đối kế toán

In [33]:
# Bỏ .head() để hiển thị toàn bộ dữ liệu
fin.balance_sheet(period='year').head()

,ticker,yearReport,CURRENT ASSETS (Bn. VND),Cash and cash equivalents (Bn. VND),Short-term investments (Bn. VND),Accounts receivable (Bn. VND),Net Inventories,Other current assets,LONG-TERM ASSETS (Bn. VND),Fixed assets (Bn. VND),...,"Inventories, Net (Bn. VND)",Other current assets (Bn. VND),Common shares (Bn. VND),Paid-in capital (Bn. VND),Long-term borrowings (Bn. VND),Advances from customers (Bn. VND),Short-term borrowings (Bn. VND),Long-term prepayments (Bn. VND),Other long-term assets (Bn. VND),MINORITY INTERESTS
0,VCI,2024,26491835561026,4743771932745,21072524575199,506858248065,0,168680805017,100288918214,37268698440,...,0,135374861200,7.180995e+12,7180994800000,0,2743133560,12573864000000,6238956911,0,0.0
1,VCI,2023,17174448616966,787897819240,15097165308797,1094491429414,0,194894059515,80686039559,23425609453,...,0,147257185100,4.375000e+12,4375000000000,0,378319774,8979275000000,7943878800,0,0.0
2,VCI,2022,14157693071824,3423501614803,10562264962864,120085485886,0,51841008271,85058244998,23496558588,...,0,46136989800,4.354999e+12,4354999010000,0,221000000,6326207142857,13290531600,0,0.0
3,VCI,2021,16568965942558,1131748599533,14998113044339,285206345277,0,153897953409,67299004559,13155825424,...,0,150714917648,3.330000e+12,3330000000000,0,52551076244,6362680000000,10702485700,0,0.0
4,VCI,2020,8312170798945,642512983590,6697916243107,221798617565,0,97527648804,70234326495,14384201512,...,0,91333803000,1.656000e+12,1656000000000,0,7971369863,2696130000000,12950546970,0,0.0

In [34]:
# Bỏ .head() để hiển thị toàn bộ dữ liệu
fin.balance_sheet(period='quarter').head()

,ticker,yearReport,lengthReport,CURRENT ASSETS (Bn. VND),Cash and cash equivalents (Bn. VND),Short-term investments (Bn. VND),Accounts receivable (Bn. VND),Net Inventories,Other current assets,LONG-TERM ASSETS (Bn. VND),...,Other current assets (Bn. VND),Common shares (Bn. VND),Paid-in capital (Bn. VND),Long-term borrowings (Bn. VND),Advances from customers (Bn. VND),Short-term borrowings (Bn. VND),Long-term prepayments (Bn. VND),Other long-term assets (Bn. VND),Goodwill,MINORITY INTERESTS
0,VCI,2024,4,26491835561026,4743771932745,21072524575199,506858248065,0,168680805017,100288918214,...,135374861200,7.180995e+12,7180994800000,0,2743133560,12573864000000,6238956911,0,0,0.0
1,VCI,2024,3,20322217963459,2543516547760,17408880681428,235746508338,0,134074225933,92945134178,...,122374861200,5.744695e+12,5744694800000,0,4431803623,10832654000000,7503462322,0,0,0.0
2,VCI,2024,2,23009916452730,3903157759657,17775135464006,931122579216,0,400500649851,95455335905,...,372374861200,4.419000e+12,4419000000000,0,1753351687,12392104000000,8879984392,0,0,0.0
3,VCI,2024,1,19458498860847,1040594399692,17454154906730,702530886335,0,261218668090,86105265555,...,227872273100,4.375000e+12,4375000000000,0,1083817322,10239557000000,9017164629,0,0,0.0
4,VCI,2023,4,17174448616966,787897819240,15097165308797,1094491429414,0,194894059515,80686039559,...,147257185100,4.375000e+12,4375000000000,0,378319774,8979275000000,7943878800,0,0,0.0

### Báo cáo kết quả kinh doanh

In [35]:
# Bỏ .head() để hiển thị toàn bộ dữ liệu
fin.income_statement(period='year').head()

,ticker,yearReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Net Sales,Cost of Sales,Gross Profit,Financial Income,...,Net other income/expenses,Profit before tax,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Minority Interest,Attributable to parent company,Sales,Other income,Other Income/Expenses
0,VCI,2024,3695525335470,0.494675,910692113293,0.851359,3695525335470,-1717402022529,1978123312941,5.063321e+10,...,2785303975,1089337104906,-178605980097,-39011516,910692113293,0,910692113293,3695525335470,3094145678,-308841703
1,VCI,2023,2472460543397,-0.216644,491904659394,-0.433927,2472460543397,-1063597101525,1408863441872,2.369615e+10,...,128411319,570138640134,-64320454739,-13913526001,491904659394,0,491904659394,2472460543397,132390105,-3978786
2,VCI,2022,3156242736345,-0.148588,868978185802,-0.420186,3156242736345,-1398531179478,1757711556867,3.554843e+10,...,43696276107,1059738713385,-250981079495,60220551912,868978185802,0,868978185802,3156242736345,44543029091,-846752984
3,VCI,2021,3707068724492,1.143320,1498718375328,0.949141,3707068724492,-1326133822522,2380934901970,2.561687e+10,...,-267786912,1850585393088,-309748513618,-42118504142,1498718375328,0,1498718375328,3707068724492,69316632,-337103544
4,VCI,2020,1729591590563,0.122423,768912289421,0.109253,1729591590563,-522004485232,1207587105331,5.858556e+09,...,621078878,951038957081,-182422798514,296130854,768912289421,0,768912289421,1729591590563,621078878,0

In [36]:
# Bỏ .head() để hiển thị toàn bộ dữ liệu
fin.income_statement(period='quarter').head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Net Sales,Cost of Sales,Gross Profit,...,Net other income/expenses,Profit before tax,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Minority Interest,Attributable to parent company,Sales,Other income,Other Income/Expenses
0,VCI,2024,4,998995850627,0.239917,218376745828,0.776135,998995850627,-519893652425,479102198202,...,21194452,253335115979,-35884665831,926295680,218376745828,0,218376745828,998995850627,23636364,-2441912
1,VCI,2024,3,974360554621,0.461496,215352225175,0.203064,974360554621,-468140246243,506220308378,...,0,264695399242,-40189361297,-9153812770,215352225175,0,215352225175,974360554621,0,0
2,VCI,2024,2,915851554761,0.828529,279206679897,1.388492,915851554761,-359336052126,556515502635,...,2826585413,343766121537,-64821621464,262179824,279206679897,0,279206679897,915851554761,2837985204,-11399791
3,VCI,2024,1,806317375461,0.615187,197756462393,1.706977,806317375461,-370032071735,436285303726,...,-62475890,227540468148,-37710331505,7926325750,197756462393,0,197756462393,806317375461,232524110,-295000000
4,VCI,2023,4,805695933425,0.011994,122950502675,3.324213,805695933425,-419422487555,386273445870,...,13012123,149131831394,-7570702516,-18610626203,122950502675,0,122950502675,805695933425,16990909,-3978786

### Báo cáo lưu chuyển tiền tệ

In [37]:
# Bỏ .head() để hiển thị toàn bộ dữ liệu
fin.cash_flow(period='year').head()

,ticker,yearReport,Net Profit/Loss before tax,Depreciation and Amortisation,Provision for credit losses,Unrealized foreign exchange gain/loss,Profit/Loss from investing activities,Interest Expense,Interest income and dividends,Operating profit before changes in working capital,...,Payments for share repurchases,Proceeds from borrowings,Repayment of borrowings,Dividends paid,Cash flows from financial activities,Net increase/decrease in cash and cash equivalents,Cash and cash equivalents,Cash and Cash Equivalents at the end of period,_Increase/Decrease in receivables,_Increase/Decrease in payables
0,VCI,2024,1089337104906,10751194638,4516800000,0,0,764124674808,-8.608679e+10,-5169139240487,...,0,28212221000000,-24737632000000,-177803580300,7371225419700,3955874113505,787897819240,4743771932745,0,65609975849
1,VCI,2023,570138640134,9679599271,11292000000,0,0,562553033255,-1.032191e+11,-5407321967895,...,0,20322010000000,-18096042142857,-522119971000,1727849074143,-2635603795563,3423501614803,787897819240,0,3923102445
2,VCI,2022,1059738713385,9647191174,0,0,154602984,477360036322,-5.948490e+10,2006811362129,...,0,15126047142857,-16579490000000,0,-1428442857143,2291753015270,1131748599533,3423501614803,0,-119194100124
3,VCI,2021,1850585393088,7496942452,-214202387,0,0,330776772616,-4.785212e+10,-5732733292320,...,0,16591566600000,-11629266600000,-730123222800,4245676777200,489235615943,642512983590,1131748599533,5939376000,88803338332
4,VCI,2020,951038957081,10634646105,-35400000,0,-500000000,173513458172,-2.094800e+10,-1673271187005,...,-852000000,7065840000000,-6233940000000,-411641446500,432858721500,-151998779012,794511762602,642512983590,57321090000,-265045502541

In [38]:
# Bỏ .head() để hiển thị toàn bộ dữ liệu
fin.income_statement(period='quarter').head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Net Sales,Cost of Sales,Gross Profit,...,Net other income/expenses,Profit before tax,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Minority Interest,Attributable to parent company,Sales,Other income,Other Income/Expenses
0,VCI,2024,4,998995850627,0.239917,218376745828,0.776135,998995850627,-519893652425,479102198202,...,21194452,253335115979,-35884665831,926295680,218376745828,0,218376745828,998995850627,23636364,-2441912
1,VCI,2024,3,974360554621,0.461496,215352225175,0.203064,974360554621,-468140246243,506220308378,...,0,264695399242,-40189361297,-9153812770,215352225175,0,215352225175,974360554621,0,0
2,VCI,2024,2,915851554761,0.828529,279206679897,1.388492,915851554761,-359336052126,556515502635,...,2826585413,343766121537,-64821621464,262179824,279206679897,0,279206679897,915851554761,2837985204,-11399791
3,VCI,2024,1,806317375461,0.615187,197756462393,1.706977,806317375461,-370032071735,436285303726,...,-62475890,227540468148,-37710331505,7926325750,197756462393,0,197756462393,806317375461,232524110,-295000000
4,VCI,2023,4,805695933425,0.011994,122950502675,3.324213,805695933425,-419422487555,386273445870,...,13012123,149131831394,-7570702516,-18610626203,122950502675,0,122950502675,805695933425,16990909,-3978786

### Chỉ số tài chính

In [39]:
# Bỏ .head() để hiển thị toàn bộ dữ liệu
fin.ratio(period='year', dropna=True).head()

    Meta                         Chỉ tiêu cơ cấu nguồn vốn              \
  ticker yearReport lengthReport (ST+LT borrowings)/Equity Debt/Equity
0    VCI       2024            5                  0.971382    1.054349
1    VCI       2023            5                  1.218152    1.340876
2    VCI       2022            5                  0.973942    1.192721
3    VCI       2021            5                  0.972610    1.543047
4    VCI       2020            5                  0.596293    0.853905

                                                        \
  Fixed Asset-To-Equity Owners' Equity/Charter Capital
0              0.002879                       1.802578
1              0.003178                       1.026491
2              0.003617                       0.904536
3              0.002011                       0.910997
4              0.003181                       0.629646

  Chỉ tiêu hiệu quả hoạt động                                              \
               Asset Turnover Fixed Asset Turnover Days Sales Outstanding
0                    0.168564           121.775022                    0.0
1                    0.156992           105.385605                    0.0
2                    0.204426           172.225781                    0.0
3                    0.296344           269.213152                    0.0
4                    0.221383           142.402909                    0.0

   ... Chỉ tiêu thanh khoản Chỉ tiêu định giá                           \
   ...   Financial Leverage               P/B Market Capital (Bn. VND)
0  ...             2.054349          2.130282           27575020032000
1  ...             2.340876          1.970499           14525000000000
2  ...             2.192721          2.866248           18617620767750
3  ...             2.543047          1.183493            7742250000000
4  ...             1.853905          2.666309           12055680000000

                                                                    \
  Outstanding Share (Mil. Shares)        P/E       P/S P/Cash Flow
0                       718099480  30.279191  7.461732   -8.148528
1                       437500000  29.528080  5.874715   -3.334822
2                       435499901  21.424727  5.898666    4.975461
3                       333000000   5.165914  2.088510   -2.064593
4                       165600000  15.678875  6.970247  -21.093469


     EPS (VND)    BVPS (VND)  EV/EBITDA
0  1268.197706  18025.783068  19.198360
1  1124.353507  16848.524590  17.525975
2  1995.357941  14914.970490  12.729467
3  4500.655782  19645.234971   5.895364
4  4643.190154  27303.662559  12.313747

[5 rows x 37 columns]

In [40]:
# Bỏ .head() để hiển thị toàn bộ dữ liệu
fin.ratio(period='quarter').head()

    Meta                         Chỉ tiêu cơ cấu nguồn vốn              \
  ticker yearReport lengthReport (ST+LT borrowings)/Equity Debt/Equity
0    VCI       2024            4                  0.971382    1.054349
1    VCI       2024            3                  1.253482    1.362305
2    VCI       2024            2                  1.398891    1.608265
3    VCI       2024            1                  1.252192    1.390102
4    VCI       2023            4                  1.218152    1.340876

                                                        \
  Fixed Asset-To-Equity Owners' Equity/Charter Capital
0              0.002879                       1.802578
1              0.003381                       1.203462
2              0.003615                       1.233606
3              0.002676                       1.138743
4              0.003178                       1.026491

  Chỉ tiêu hiệu quả hoạt động                                              \
               Asset Turnover Fixed Asset Turnover Days Sales Outstanding
0                    0.168564           121.775022                    0.0
1                    0.174413           131.475148                    0.0
2                    0.166335           129.528632                    0.0
3                    0.162937           130.111085                    0.0
4                    0.156992           105.385605                    0.0

   ... Chỉ tiêu thanh khoản Chỉ tiêu định giá                           \
   ...   Financial Leverage               P/B Market Capital (Bn. VND)
0  ...             2.054349          2.130282           27575020032000
1  ...             2.362305          1.806066           22871468438000
2  ...             2.608265          2.379972           21083029916000
3  ...             2.390102          2.571899           21167010000000
4  ...             2.340876          3.092259           22793750000000

                                                                    \
  Outstanding Share (Mil. Shares)        P/E       P/S P/Cash Flow
0                       718099480  24.966141  7.461732   -6.718717
1                       718099480  23.303298  6.530553  -17.723150
2                       574469480  26.866048  6.599683   -4.975656
3                       441900000  33.973894  7.615216   -4.399652
4                       437500000  46.238494  9.219055   -5.222052


    EPS (VND)    BVPS (VND)  EV/EBITDA
0  304.103752  18025.783068  19.447277
1  299.891911  17635.011093  17.958349
2  486.025263  15420.349585  17.950658
3  447.514058  18624.368974  20.739556
4  281.029720  16848.524590  22.946233

[5 rows x 37 columns]

## 4. Trạng thái niêm yết

In [10]:
from vnstock_data import Listing

Listing().all_symbols()

,code,type,exchange,status,company_name,company_name_eng,short_name,listed_date,delisted_date,company_id,isin,tax_code,short_name_eng,index_code
0,ENF,IFC,UPCOM,delisted,Quỹ Đầu tư Năng động Eastspring Investments Vi...,Eastspring Investments Vietnam Navigator Fund,Quỹ đầu tư ENF,2001-01-01,2001-01-01,3903,NaN,NaN,NaN,NaN
1,VFMVFA,IFC,HOSE,delisted,Quỹ Đầu tư năng động Việt Nam,Vietnam Active Fund,NaN,2010-08-09,2013-03-11,2862,VN000VFMVFA5,NaN,NaN,NaN
2,FUCVREIT,IFC,HOSE,listed,Quỹ đầu tư bất động sản Techcom Việt Nam,Techcom Vietnam REIT Fund,Quỹ BĐS Techcom VN,2017-02-27,NaN,5169,VN0FUCVREIT6,0102995749-001,NaN,NaN
3,VESAF,IFC,HOSE,listed,Công ty Cổ phần Quản lý Quỹ VinaCapital,VinaCaptital Fund Management JSC,Quỹ ETF VinaCapital VN100,2020-07-21,NaN,10762,NaN,0305655145,NaN,NaN
4,MAFPF1,IFC,HOSE,delisted,Quỹ đầu tư tăng trưởng Manulife,Manulife Progressive Fund,NaN,2007-12-28,2014-08-21,2186,VN000MAFPF14,0303861449,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1944,MCP,STOCK,HOSE,listed,Công ty Cổ phần In và Bao bì Mỹ Châu,MYCHAU PRINTING AND PACKAGING CORPORATION,Bao bì Mỹ Châu,2006-12-28,NaN,1348,VN000000MCP3,0301671386,My Chau Print & Packaging,NaN
1945,MDG,STOCK,HOSE,listed,Công ty Cổ phần Miền Đông,Mien Dong Joint Stock Company,CTCP Miền Đông,2011-01-12,NaN,3102,VN000000MDG0,3600256545,Mien Dong Construction,NaN
1946,BCI,STOCK,HOSE,delisted,Công ty Cổ phần Đầu tư xây dựng Bình Chánh,Binh Chanh Construction Investment Shareholdin...,Đầu tư XD Bình Chánh,2009-03-16,2018-02-23,2443,VN000000BCI1,0301881016,NaN,NaN
1947,AAM,STOCK,HOSE,listed,Công ty Cổ phần Thủy sản Mekong,MekongFisheries Joint Stock Company,Thủy sản Mekong,2009-09-24,NaN,2498,VN000000AAM9,1800448811,Mekong Fisheries,NaN
1948,VTB,STOCK,HOSE,listed,Công ty Cổ phần Viettronics Tân Bình,Viettronics Tan Binh Joint Stock Company,Viettronics Tân Bình,2006-12-27,NaN,1356,VN000000VTB8,0300391837,Viettronics Tan Binh,NaN

## 5. Top cổ phiếu

In [11]:
from vnstock_data import TopStock
top = TopStock()

### Top tăng giá

In [12]:
top.gainer()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,HHS,VNINDEX,9.84,2025-03-27 15:59,0.64,6.956522,3.879792e+10,2490555.0,163.337088,2565805.0,38.974123,7.794825,1000000.0,1.960000e+09,200000.0
1,NNC,VNINDEX,30.85,2025-03-27 15:59,2.00,6.932409,5.809635e+09,26700.0,710.112360,26700.0,0.000000,0.000000,0.0,0.000000e+00,0.0
2,HVH,VNINDEX,11.85,2025-03-27 15:59,0.75,6.756757,6.573800e+09,367090.0,156.310442,416090.0,0.000000,17.303949,360000.0,6.408000e+08,72000.0
3,GIL,VNINDEX,17.90,2025-03-27 15:59,0.75,4.373178,2.858629e+10,581140.0,275.252091,581140.0,0.000000,0.000000,0.0,0.000000e+00,0.0
4,SMC,VNINDEX,6.50,2025-03-27 15:59,0.25,4.000000,1.768744e+10,804135.0,332.668022,804135.0,0.000000,0.000000,0.0,0.000000e+00,0.0
5,SHB,VNINDEX,12.70,2025-03-27 15:59,0.45,3.673469,8.218865e+11,48824855.0,134.684681,57761257.4,7.537925,6.906013,19945000.0,4.632323e+10,3989000.0
6,ABT,VNINDEX,45.90,2025-03-27 15:59,1.60,3.611738,3.007800e+08,18125.0,36.413793,18125.0,0.000000,0.000000,0.0,0.000000e+00,0.0
7,SHI,VNINDEX,15.15,2025-03-27 15:59,0.50,3.412969,5.061000e+09,417725.0,82.302951,1228220.0,547.133250,213.642507,13120000.0,3.877760e+10,2624000.0
8,TCH,VNINDEX,18.80,2025-03-27 15:59,0.60,3.296703,2.754795e+11,6950560.0,212.955503,6951560.0,0.000000,0.000000,0.0,0.000000e+00,0.0
9,LBM,VNINDEX,30.80,2025-03-27 15:59,0.80,2.666667,2.538120e+09,103775.0,80.077090,103775.0,0.000000,0.000000,0.0,0.000000e+00,0.0

### Top giảm giá

In [13]:
top.loser()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,VAF,VNINDEX,18.80,2025-03-27 15:59,-1.20,-6.000000,1.410700e+08,13910.0,50.323508,13910.0,0.000000,0.000000,0.0,0.000000e+00,0.0
1,LGL,VNINDEX,3.21,2025-03-27 15:59,-0.15,-4.464286,3.615230e+08,124320.0,89.446589,124320.0,0.000000,0.000000,0.0,0.000000e+00,0.0
2,OGC,VNINDEX,4.95,2025-03-27 15:59,-0.21,-4.069767,3.563266e+09,256785.0,278.443055,259785.0,0.000000,0.000000,0.0,0.000000e+00,0.0
3,VRC,VNINDEX,14.05,2025-03-27 15:59,-0.55,-3.767123,1.431910e+09,51685.0,193.673213,51685.0,0.000000,0.000000,0.0,0.000000e+00,0.0
4,GEE,VNINDEX,69.50,2025-03-27 15:59,-2.50,-3.472222,9.749382e+10,1210010.0,113.618896,1227710.0,0.000000,3.828266,235000.0,2.998600e+09,47000.0
5,PHC,VNINDEX,5.31,2025-03-27 15:59,-0.18,-3.278689,6.923520e+08,60745.0,212.198535,131745.0,0.000000,0.000000,0.0,0.000000e+00,0.0
6,YBM,VNINDEX,13.95,2025-03-27 15:59,-0.45,-3.125000,3.170150e+08,50635.0,44.435667,56865.0,0.000000,0.000000,0.0,0.000000e+00,0.0
7,PET,VNINDEX,21.70,2025-03-27 15:59,-0.65,-2.908277,1.570116e+10,537780.0,132.861021,606780.0,41.201094,22.083787,670000.0,3.086820e+09,134000.0
8,SGR,VNINDEX,37.70,2025-03-27 15:59,-1.10,-2.835052,1.960825e+09,61965.0,83.434197,65905.0,0.000000,0.000000,0.0,0.000000e+00,0.0
9,KHG,VNINDEX,5.61,2025-03-27 15:59,-0.16,-2.772964,2.303872e+10,8536595.0,47.659518,8536595.0,0.000000,0.000000,0.0,0.000000e+00,0.0

### Top theo GTGD lớn nhất

In [14]:
top.value()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,SHB,VNINDEX,12.70,2025-03-27 15:59,0.45,3.673469,8.218865e+11,48824855.0,134.684681,57761257.40,7.537925,6.906013,19945000.0,4.632323e+10,3989000.0
1,FPT,VNINDEX,126.20,2025-03-27 15:59,3.20,2.601626,8.016808e+11,6590470.0,98.087086,7094209.75,10.712962,6.891818,2444600.0,6.112783e+10,488920.0
2,MSN,VNINDEX,69.40,2025-03-27 15:59,1.10,1.610542,5.056319e+11,5097365.0,141.941964,5853785.00,0.000000,7.123596,2085000.0,2.853218e+10,417000.0
3,HCM,VNINDEX,30.60,2025-03-27 15:59,-0.60,-1.923077,4.469858e+11,10441740.0,138.749864,10658040.00,0.000000,0.750607,400000.0,2.552136e+09,80000.0
4,VHM,VNINDEX,51.20,2025-03-27 15:59,-0.30,-0.582524,4.039203e+11,12918410.0,61.186322,15247481.00,18.240390,12.542924,9562400.0,9.893568e+10,1912480.0
5,SSI,VNINDEX,26.30,2025-03-27 15:59,-0.20,-0.754717,3.980601e+11,28360130.0,53.128811,29679134.85,0.520558,1.107847,1643997.0,8.838138e+09,328799.4
6,VND,VNINDEX,15.55,2025-03-27 15:59,0.30,1.967213,3.482074e+11,24770630.0,91.108300,24824030.00,0.000000,0.385111,478000.0,1.452940e+09,95600.0
7,HPG,VNINDEX,27.50,2025-03-27 15:59,-0.05,-0.181488,3.312106e+11,24941830.0,48.150837,26685920.00,35.835377,21.314761,28440200.0,1.544145e+11,5688040.0
8,VIX,VNINDEX,12.55,2025-03-27 15:59,-0.05,-0.396825,3.167951e+11,47586540.0,52.685486,50497990.00,0.099014,2.663472,6725000.0,1.603680e+10,1345000.0
9,MBB,VNINDEX,23.90,2025-03-27 15:59,-0.10,-0.416667,2.977707e+11,21665840.0,57.352034,24338253.55,2.465255,8.160816,9931000.0,4.889844e+10,1986200.0

### Top theo KLGD

In [15]:
top.volume()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,NNC,VNINDEX,30.85,2025-03-27 15:59,2.00,6.932409,5.809635e+09,26700.0,710.112360,26700.0,0.0,0.0,0.0,0.0,0.0
1,TLD,VNINDEX,6.29,2025-03-27 15:59,0.09,1.451613,8.168385e+09,260400.0,502.918587,260400.0,0.0,0.0,0.0,0.0,0.0
2,SMC,VNINDEX,6.50,2025-03-27 15:59,0.25,4.000000,1.768744e+10,804135.0,332.668022,804135.0,0.0,0.0,0.0,0.0,0.0
3,TNT,VNINDEX,4.90,2025-03-27 15:59,0.01,0.204499,4.242411e+09,262155.0,328.851252,262155.0,0.0,0.0,0.0,0.0,0.0
4,OGC,VNINDEX,4.95,2025-03-27 15:59,-0.21,-4.069767,3.563266e+09,256785.0,278.443055,259785.0,0.0,0.0,0.0,0.0,0.0
5,GIL,VNINDEX,17.90,2025-03-27 15:59,0.75,4.373178,2.858629e+10,581140.0,275.252091,581140.0,0.0,0.0,0.0,0.0,0.0
6,PGC,VNINDEX,15.70,2025-03-27 15:59,-0.10,-0.632911,1.251895e+09,30900.0,260.841424,30900.0,0.0,0.0,0.0,0.0,0.0
7,PTL,VNINDEX,2.65,2025-03-27 15:59,-0.01,-0.375940,1.824880e+08,29355.0,233.691024,29355.0,0.0,0.0,0.0,0.0,0.0
8,SVT,VNINDEX,12.30,2025-03-27 15:59,0.00,0.000000,2.893600e+08,10525.0,223.277910,10525.0,0.0,0.0,0.0,0.0,0.0
9,TCH,VNINDEX,18.80,2025-03-27 15:59,0.60,3.296703,2.754795e+11,6950560.0,212.955503,6951560.0,0.0,0.0,0.0,0.0,0.0

### Top GD thoả thuận

In [16]:
top.deal()

,symbol,index,last_price,last_updated,price_change_1d,price_change_pct_1d,accumulated_value,avg_volume_20d,volume_spike_20d_pct,total_volume_avg_20d,deal_volume_spike_20d_pct,deal_volume_spike_5d_20d_pct,deal_volume_sum_5d,deal_value_avg_5d,deal_volume_avg_5d
0,MHC,VNINDEX,7.46,2025-03-27 15:59,0.01,0.134228,5.319900e+07,76770.0,9.118145,161770.00,1050.874699,210.174940,1700000.0,2.363000e+09,340000.0
1,HII,VNINDEX,4.67,2025-03-27 15:59,-0.03,-0.638298,3.131800e+07,76475.0,8.891795,435750.00,820.539300,329.799197,7185500.0,6.754370e+09,1437100.0
2,SHI,VNINDEX,15.15,2025-03-27 15:59,0.50,3.412969,5.061000e+09,417725.0,82.302951,1228220.00,547.133250,213.642507,13120000.0,3.877760e+10,2624000.0
3,VIC,VNINDEX,57.10,2025-03-27 15:59,0.10,0.175439,2.614665e+11,7051150.0,64.800777,11502915.00,227.312381,105.039636,60413100.0,7.080777e+11,12082620.0
4,CDC,VNINDEX,21.00,2025-03-27 15:59,0.10,0.478469,2.594550e+09,84730.0,149.651835,228975.00,171.154056,162.541762,1860900.0,7.383957e+09,372180.0
5,APG,VNINDEX,10.55,2025-03-27 15:59,0.00,0.000000,3.413905e+09,504655.0,64.578772,952050.00,169.633948,181.696339,8649200.0,1.700231e+10,1729840.0
6,TLG,VNINDEX,57.80,2025-03-27 15:59,0.90,1.581722,5.093570e+09,104910.0,83.881422,119510.00,142.247511,28.449502,170000.0,1.968740e+09,34000.0
7,SSB,VNINDEX,19.60,2025-03-27 15:59,0.05,0.255754,3.506033e+10,1850275.0,97.018011,8970059.15,127.245538,144.137288,64646000.0,2.543928e+11,12929200.0
8,KDC,VNINDEX,56.30,2025-03-27 15:59,-0.10,-0.177305,2.917010e+10,360265.0,144.116137,1288987.00,119.512454,105.877887,6823761.0,7.647826e+10,1364752.2
9,CTF,VNINDEX,19.90,2025-03-27 15:59,-0.10,-0.500000,4.910515e+09,241620.0,101.895538,549515.10,87.604508,79.393633,2181400.0,8.856600e+09,436280.0

### Top NĐTNN mua ròng

In [17]:
top.foreign_buy(date='2024-08-16')

  symbol        date     net_value
0    MWG  2024-08-16  1.015998e+11
1    CTG  2024-08-16  6.709855e+10
2    DIG  2024-08-16  6.705117e+10
3    MSN  2024-08-16  6.318864e+10
4    VCI  2024-08-16  5.041683e+10
5    VND  2024-08-16  3.089996e+10
6    NVL  2024-08-16  3.054193e+10
7    DPM  2024-08-16  2.839805e+10
8    DGC  2024-08-16  2.769208e+10
9    FPT  2024-08-16  2.629880e+10

### Top NĐTNN bán ròng

In [18]:
top.foreign_sell(date='2024-08-16')

     symbol        date     net_value
0       VHM  2024-08-16 -3.136147e+11
1       HPG  2024-08-16 -1.804457e+11
2       TCB  2024-08-16 -1.083005e+11
3       HSG  2024-08-16 -5.660693e+10
4       VPB  2024-08-16 -4.944804e+10
5  FUEVFVND  2024-08-16 -3.769779e+10
6       FRT  2024-08-16 -3.130877e+10
7       HDB  2024-08-16 -2.534124e+10
8       QNS  2024-08-16 -1.809028e+10
9       NLG  2024-08-16 -1.657578e+10

## 6. Giá hàng hoá

In [19]:
from vnstock_data import CommodityPrice

# Khởi tạo đối tượng CommodityPrice với ngày mặc định
commodity = CommodityPrice(start="2022-01-03", end="2024-12-31")

# Lấy dữ liệu giá vàng
gold_vn = commodity.gold_vn()  # Giá vàng Việt Nam (mua vào)
print("Gold VN:\n", gold_vn)

gold_global = commodity.gold_global()  # Giá vàng thế giới
print("Gold Global:\n", gold_global)

# Lấy dữ liệu giá xăng
gas_vn = commodity.gas_vn()  # Giá xăng RON92
print("Gas VN:\n", gas_vn)

oil_crude = commodity.oil_crude()  # Giá dầu thô
print("Oil Crude:\n", oil_crude)

# Lấy dữ liệu khí thiên nhiên
gas_natural = commodity.gas_natural()  # Giá khí thiên nhiên
print("Gas Natural:\n", gas_natural)

# Lấy dữ liệu giá than
coke = commodity.coke()  # Giá than cốc
print("Coke:\n", coke)

# Lấy dữ liệu giá thép
steel_d10 = commodity.steel_d10()  # Giá thép D10
print("Steel D10:\n", steel_d10)

steel_hrc = commodity.steel_hrc()  # Giá thép HRC
print("Steel HRC:\n", steel_hrc)

# Lấy dữ liệu giá quặng sắt
iron_ore = commodity.iron_ore()  # Giá quặng sắt
print("Iron Ore:\n", iron_ore)

# Lấy dữ liệu giá phân bón
fertilizer_ure = commodity.fertilizer_ure()  # Giá phân ure
print("Fertilizer URE:\n", fertilizer_ure)

# Lấy dữ liệu giá nông sản
soybean = commodity.soybean()  # Giá đậu tương
print("Soybean:\n", soybean)

corn = commodity.corn()  # Giá ngô (bắp)
print("Corn:\n", corn)

sugar = commodity.sugar()  # Giá đường
print("Sugar:\n", sugar)

# Lấy dữ liệu giá heo hơi
pork_north_vn = commodity.pork_north_vn()  # Giá heo hơi miền Bắc Việt Nam
print("Pork North VN:\n", pork_north_vn)

pork_china = commodity.pork_china()  # Giá heo hơi Trung Quốc
print("Pork China:\n", pork_china)

Gold VN:
                 buy     sell
time
2022-01-03  60900.0  61600.0
2022-01-04  61000.0  61700.0
2022-01-05  60750.0  61450.0
2022-01-06  60900.0  61600.0
2022-01-09  60900.0  61650.0
...             ...      ...
2024-12-25  82300.0  84300.0
2024-12-26  82500.0  84500.0
2024-12-27  82700.0  84700.0
2024-12-28  82700.0  84700.0
2024-12-30  82500.0  84500.0

[791 rows x 2 columns]
Gold Global:
               open    high     low   close    volume
time
2022-01-03  1830.1  1833.0  1798.2  1800.1  168305.0
2022-01-04  1801.1  1817.2  1798.1  1814.6  167708.0
2022-01-05  1815.2  1830.7  1808.2  1825.1  173344.0
2022-01-06  1810.6  1811.6  1785.4  1789.2  238644.0
2022-01-07  1791.0  1798.4  1781.3  1797.4  238931.0
...            ...     ...     ...     ...       ...
2024-12-23  2639.1  2646.8  2623.2  2628.2  100814.0
2024-12-24  2629.4  2635.8  2624.2  2635.5   52221.0
2024-12-26  2638.0  2655.7  2634.1  2653.9   77712.0
2024-12-27  2653.7  2654.6  2625.2  2631.9   92262.0
2024-12-30  2636.1  2640.7  2608.4  2618.1  110915.0

[822 rows x 5 columns]
Gas VN:
             ron95  ron92  oil_do
time
2022-01-15  23.87  23.15   18.23
2022-01-16  23.87  23.15   18.23
2022-01-17  23.87  23.15   18.23
2022-01-18  23.87  23.15   18.23
2022-01-19  23.87  23.15   18.23
...           ...    ...     ...
2024-12-26  20.54  19.81   18.63
2024-12-27  20.54  19.81   18.63
2024-12-28  20.54  19.81   18.63
2024-12-29  20.54  19.81   18.63
2024-12-30  20.54  19.81   18.63

[1000 rows x 3 columns]
Oil Crude:
              open   high    low  close    volume
time
2022-01-03  75.69  76.46  74.27  76.08  317628.0
2022-01-04  76.02  77.64  75.70  76.99  372848.0
2022-01-05  77.18  78.58  76.51  77.85  397898.0
2022-01-06  77.24  80.24  76.73  79.46  476665.0
2022-01-07  79.62  80.47  78.52  78.90  414434.0
...           ...    ...    ...    ...       ...
2024-12-23  69.40  69.94  68.59  69.24  174319.0
2024-12-24  69.56  70.43  69.36  70.10  108539.0
2024-12-26  70.20  70.75  69.33  69.62  128387.0
2024-12-27  69.68  70.75  69.44  70.60  158886.0
2024-12-30  70.42  71.56  70.12  70.99  183540.0

[823 rows x 5 columns]
Gas Natural:
              open   high    low  close   volume
time
2022-01-03  3.725  3.855  3.635  3.815   5288.0
2022-01-04  3.830  3.945  3.705  3.715   5781.0
2022-01-05  3.750  3.895  3.720  3.880   4507.0
2022-01-06  3.840  3.930  3.805  3.810   5656.0
2022-01-07  3.865  3.980  3.785  3.915   5335.0
...           ...    ...    ...    ...      ...
2024-12-23  3.500  3.545  3.285  3.345   4071.0
2024-12-24  3.385  3.510  3.360  3.505   4559.0
2024-12-26  3.520  3.525  3.250  3.320   5439.0
2024-12-27  3.325  3.450  3.290  3.385   6227.0
2024-12-30  3.650  4.205  3.645  3.935  18093.0

[822 rows x 5 columns]
Coke:
               open    high     low   close  volume
time
2022-01-03  151.45  151.45  151.45  151.45     2.0
2022-01-04  166.50  168.00  161.00  161.10   383.0
2022-01-05  165.00  165.00  161.00  161.65   171.0
2022-01-06  175.00  181.00  175.00  180.00   100.0
2022-01-07  195.00  196.75  177.00  177.00   536.0
...            ...     ...     ...     ...     ...
2024-12-23  125.50  125.50  125.50  125.50    29.0
2024-12-24  125.00  125.00  125.00  125.00    10.0
2024-12-26  126.50  126.50  126.50  126.50     0.0
2024-12-27  126.40  126.40  126.30  126.30    55.0
2024-12-30  125.75  125.90  125.75  125.90    75.0

[772 rows x 5 columns]
Steel D10:
                 close
time
2022-01-14  16.410000
2022-01-15  16.410000
2022-01-16  16.683333
2022-01-17  16.683333
2022-01-18  16.683333
...               ...
2024-12-26  13.940000
2024-12-27  13.940000
2024-12-28  13.940000
2024-12-29  13.940000
2024-12-30  13.940000

[1000 rows x 1 columns]
Steel HRC:
               open    high     low   close  volume
time
2022-01-03  1435.0  1439.0  1435.0  1438.0    32.0
2022-01-04  1435.0  1440.0  1435.0  1435.0   642.0
2022-01-05  1435.0  1435.0  1425.0  1426.0   312.0
2022-01-06  1420.0  1425.0  1410.0  1420.0   263.0
2022-01-07  1419.0  1420.0  1405.0  1415.0   176.0
...            ...     ...     ...     ...     ...
2024-12-23   685.0   685.0   677.0   683.0    92.0
2024-12-24   729.0   729.0   723.0   725.0   144.0
2024-12-26   720.0   740.0   720.0   720.0    60.0
2024-12-27   730.0   730.0   730.0   730.0   100.0
2024-12-30   725.0   732.0   718.0   725.0   115.0

[752 rows x 5 columns]
Iron Ore:
               open    high     low   close  volume
time
2022-01-03  120.40  120.40  120.40  120.40     0.0
2022-01-04  120.91  120.91  120.91  120.91     0.0
2022-01-05  124.14  124.14  124.14  124.14   200.0
2022-01-06  125.94  125.94  125.94  125.94     0.0
2022-01-07  126.21  126.21  126.21  126.21     0.0
...            ...     ...     ...     ...     ...
2024-12-23  103.84  103.84  103.84  103.84     0.0
2024-12-24  104.08  104.08  104.08  104.08     0.0
2024-12-26  104.08  104.08  104.08  104.08     0.0
2024-12-27  103.90  103.90  103.90  103.90     0.0
2024-12-30  100.73  100.73  100.73  100.73     0.0

[757 rows x 5 columns]
Fertilizer URE:
              open   high    low  close  volume
time
2022-01-03  842.5  842.5  842.5  842.5     0.0
2022-01-04  842.5  842.5  842.5  842.5     0.0
2022-01-05  830.0  830.0  830.0  830.0     0.0
2022-01-06  835.0  835.0  835.0  835.0     0.0
2022-01-07  835.0  835.0  835.0  835.0     0.0
...           ...    ...    ...    ...     ...
2024-12-23  366.0  366.0  366.0  366.0     0.0
2024-12-24  366.0  366.0  366.0  366.0     0.0
2024-12-26  366.0  366.0  366.0  366.0     0.0
2024-12-27  369.0  369.0  369.0  369.0     0.0
2024-12-30  369.0  369.0  369.0  369.0     0.0

[729 rows x 5 columns]
Soybean:
                open     high      low    close    volume
time
2022-01-03  1349.00  1368.50  1342.00  1355.50   90234.0
2022-01-04  1356.00  1392.25  1355.50  1389.75  122661.0
2022-01-05  1389.00  1399.00  1381.50  1394.75   96172.0
2022-01-06  1390.50  1393.75  1370.00  1387.25   99489.0
2022-01-07  1388.00  1415.00  1376.00  1410.25  129914.0
...             ...      ...      ...      ...       ...
2024-12-23   979.50   984.00   972.75   975.50  105210.0
2024-12-24   974.50   981.75   971.75   981.25   64012.0
2024-12-26   985.00   998.00   981.00   997.25  135969.0
2024-12-27   995.75   998.25   988.50   989.75  104442.0
2024-12-30   994.25  1004.50   986.75   991.75  140332.0

[752 rows x 5 columns]
Corn:
               open    high     low   close    volume
time
2022-01-03  599.00  603.50  584.75  589.25  146023.0
2022-01-04  591.75  611.25  591.50  609.50  210268.0
2022-01-05  608.50  609.75  601.25  602.25  148499.0
2022-01-06  601.25  605.75  596.00  603.75  151442.0
2022-01-07  605.25  608.25  599.00  606.75  140371.0
...            ...     ...     ...     ...       ...
2024-12-23  446.00  448.25  445.25  447.75  132878.0
2024-12-24  447.25  448.75  446.75  448.50   88153.0
2024-12-26  448.50  454.25  448.50  453.75  176165.0
2024-12-27  453.25  455.00  452.25  454.00  162024.0
2024-12-30  453.75  458.50  449.75  452.25  217069.0

[811 rows x 5 columns]
Sugar:
              open   high    low  close   volume
time
2022-01-03  18.94  19.01  18.68  18.74  20398.0
2022-01-04  18.75  18.85  18.62  18.75  40168.0
2022-01-05  18.80  18.80  18.32  18.34  59414.0
2022-01-06  18.31  18.39  18.15  18.19  46247.0
2022-01-07  18.26  18.44  17.99  18.05  46856.0
...           ...    ...    ...    ...      ...
2024-12-23  19.60  19.79  19.42  19.54  39966.0
2024-12-24  19.60  19.82  19.50  19.54  22290.0
2024-12-26  19.51  19.54  19.17  19.26  26005.0
2024-12-27  19.24  19.45  19.18  19.37  34311.0
2024-12-30  19.37  19.66  19.05  19.13  43046.0

[753 rows x 5 columns]
Pork North VN:
               close
time
2022-01-10  58000.0
2022-01-17  56562.5
2022-01-24  54312.5
2022-02-03  53987.5
2022-02-10  54037.5
...             ...
2024-12-24  68600.0
2024-12-25  68300.0
2024-12-26  68100.0
2024-12-29  67700.0
2024-12-30  67900.0

[409 rows x 1 columns]
Pork China:
             close
time
2022-01-08  14.52
2022-01-15  13.67
2022-01-22  13.33
2022-02-01  13.21
2022-02-08  12.88
...           ...
2024-11-26  17.10
2024-12-03  16.92
2024-12-10  16.65
2024-12-17  16.56
2024-12-24  16.44

[157 rows x 1 columns]

## 7. Định giá thị trường

In [20]:
from vnstock_data import Market

market = Market(index='HNXINDEX')

In [21]:
market.pe(duration='5Y')

                   pe
reportDate
2020-03-30   8.424134
2020-03-31   8.382520
2020-04-01   8.554329
2020-04-03   8.747054
2020-04-06   9.092409
...               ...
2025-03-20  22.880070
2025-03-21  22.999385
2025-03-24  22.957261
2025-03-25  22.899081
2025-03-26  22.866964

[1243 rows x 1 columns]

In [22]:
market.pb(duration='5Y')

                  pb
reportDate
2020-03-30  0.885796
2020-03-31  0.877108
2020-04-01  0.895084
2020-04-03  0.915336
2020-04-06  0.951569
...              ...
2025-03-20  1.627838
2025-03-21  1.633020
2025-03-24  1.630000
2025-03-25  1.625086
2025-03-26  1.614746

[1243 rows x 1 columns]

In [23]:
market.evaluation(duration='5M')

                   pe        pb
reportDate
2024-10-28  15.823710  1.377233
2024-10-29  16.021799  1.383129
2024-10-30  16.039316  1.377695
2024-10-31  15.851675  1.370266
2024-11-01  15.432620  1.368654
...               ...       ...
2025-03-20  22.880070  1.627838
2025-03-21  22.999385  1.633020
2025-03-24  22.957261  1.630000
2025-03-25  22.899081  1.625086
2025-03-26  22.866964  1.614746

[102 rows x 2 columns]